/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <stdio.h>
#include <sys/time.h>

static int last_ticket = 0;

ticket_res *
get_ticket_1_svc(ticket_req *argp, struct svc_req *rqstp)
{
    static ticket_res result;
    struct timeval tv;

    gettimeofday(&tv, NULL);

    result.ticket = ++last_ticket;
    result.served_sec  = (u_int)tv.tv_sec;
    result.served_usec = (u_int)tv.tv_usec;

    printf("Client pid=%d -> ticket=%d at %u.%06u\n",
           argp->pid, result.ticket, result.served_sec, result.served_usec);

    return &result;
}
