/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "bakery.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

ticket_res *
get_ticket_1(ticket_req *argp, CLIENT *clnt)
{
	static ticket_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_TICKET,
		(xdrproc_t) xdr_ticket_req, (caddr_t) argp,
		(xdrproc_t) xdr_ticket_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
