/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <time.h>

static volatile sig_atomic_t running = 1;

static void on_sigint(int signo)
{
    (void)signo;
    running = 0;
}

int main(int argc, char *argv[])
{
    if (argc < 2) {
        printf("usage: %s server_host\n", argv[0]);
        return 1;
    }

    signal(SIGINT, on_sigint);

    CLIENT *clnt = clnt_create(argv[1], BAKERY_PROG, BAKERY_VER, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(argv[1]);
        return 1;
    }

    ticket_req req;
    req.pid = (int)getpid();

    while (running) {
        ticket_res *res = get_ticket_1(&req, clnt);

        if (res == NULL) {
            /* Если нажали Ctrl+C во время ожидания — просто выходим */
            if (!running) break;

            clnt_perror(clnt, "call failed");
            break;
        }

        /* Форматируем время обслуживания */
        time_t t = (time_t)res->served_sec;
        struct tm tm;
        char buf[64];

        localtime_r(&t, &tm);
        strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", &tm);

        printf("Got ticket: %d  served_at: %s.%06u\n",
               res->ticket, buf, res->served_usec);

        fflush(stdout);

        /* чтобы не спамить сервер бесконечно — можно убрать/изменить */
        usleep(200000); // 0.2 сек
    }

    printf("Client exiting...\n");
    clnt_destroy(clnt);
    return 0;
}
