/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bakery.h"

bool_t
xdr_ticket_req (XDR *xdrs, ticket_req *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->pid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ticket_res (XDR *xdrs, ticket_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ticket))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->served_sec))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->served_usec))
		 return FALSE;
	return TRUE;
}
