/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct ticket_req {
	int pid;
};
typedef struct ticket_req ticket_req;

struct ticket_res {
	int ticket;
	u_int served_sec;
	u_int served_usec;
};
typedef struct ticket_res ticket_res;

#define BAKERY_PROG 0x20000011
#define BAKERY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_TICKET 1
extern  ticket_res * get_ticket_1(ticket_req *, CLIENT *);
extern  ticket_res * get_ticket_1_svc(ticket_req *, struct svc_req *);
extern int bakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_TICKET 1
extern  ticket_res * get_ticket_1();
extern  ticket_res * get_ticket_1_svc();
extern int bakery_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ticket_req (XDR *, ticket_req*);
extern  bool_t xdr_ticket_res (XDR *, ticket_res*);

#else /* K&R C */
extern bool_t xdr_ticket_req ();
extern bool_t xdr_ticket_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
